!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  emitter_always_on: false
  emitter_enabled: 0
  emitter_on_off: false
  enable_auto_exposure: true
  error_polling_enabled: true
  exposure: 8500
  frames_queue_size: 16
  gain: 16
  global_time_enabled: true
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      emitter_always_on: false
      emitter_enabled: 0
      emitter_on_off: false
      enable_auto_exposure: true
      error_polling_enabled: true
      exposure: 8500
      frames_queue_size: 16
      gain: 16
      global_time_enabled: true
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      hdr_enabled: false
      id: 0
      inter_cam_sync_mode: 0
      laser_power: 150.0
      name: Default
      output_trigger_enabled: false
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      sequence_id: 0
      sequence_name: 0
      sequence_size: 2
      state: true
      type: ''
      visual_preset: 0
    state: []
  hdr_enabled: false
  inter_cam_sync_mode: 0
  laser_power: 150.0
  output_trigger_enabled: false
  sequence_id: 0
  sequence_name: 0
  sequence_size: 2
  visual_preset: 0
state: []
